package sap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZSPF_BAPI_SAIDA", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZSPFBAPISAIDA {


    /**
     * 
     * @param fimValidade
     * @param p2006
     * @param inicioValidade
     * @param usuario
     * @param p9100
     * @param matriculas
     * @return
     *     returns io.cronapp.sap.ZBapireturn1
     */
    @WebMethod(operationName = "ZhrplanferiasSaida", action = "http://www.sap.com/ZhrplanferiasSaida")
    @WebResult(name = "Return", targetNamespace = "")
    @RequestWrapper(localName = "ZhrplanferiasSaida", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "io.cronapp.sap.ZhrplanferiasSaida")
    @ResponseWrapper(localName = "ZhrplanferiasSaidaResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "io.cronapp.sap.ZhrplanferiasSaidaResponse")
    public ZBapireturn1 zhrplanferiasSaida(
        @WebParam(name = "FimValidade", targetNamespace = "")
        String fimValidade,
        @WebParam(name = "InicioValidade", targetNamespace = "")
        String inicioValidade,
        @WebParam(name = "Matriculas", targetNamespace = "")
        ZctHrBapiPernr matriculas,
        @WebParam(name = "Usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "P2006", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZctHrBapiP2006> p2006,
        @WebParam(name = "P9100", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZctHrBapiP9100> p9100);

}
