
package sap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZSPF_BAPI_ENTRADA", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/build/cronapp/wsdl_entrada.xml")
public class ZSPFBAPIENTRADA_Service
    extends Service
{

    private final static URL ZSPFBAPIENTRADA_WSDL_LOCATION;
    private final static WebServiceException ZSPFBAPIENTRADA_EXCEPTION;
    private final static QName ZSPFBAPIENTRADA_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZSPF_BAPI_ENTRADA");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/build/cronapp/wsdl_entrada.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZSPFBAPIENTRADA_WSDL_LOCATION = url;
        ZSPFBAPIENTRADA_EXCEPTION = e;
    }

    public ZSPFBAPIENTRADA_Service() {
        super(__getWsdlLocation(), ZSPFBAPIENTRADA_QNAME);
    }

    public ZSPFBAPIENTRADA_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZSPFBAPIENTRADA_QNAME, features);
    }

    public ZSPFBAPIENTRADA_Service(URL wsdlLocation) {
        super(wsdlLocation, ZSPFBAPIENTRADA_QNAME);
    }

    public ZSPFBAPIENTRADA_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZSPFBAPIENTRADA_QNAME, features);
    }

    public ZSPFBAPIENTRADA_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZSPFBAPIENTRADA_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZSPFBAPIENTRADA
     */
    @WebEndpoint(name = "ZSPF_BAPI_ENTRADA")
    public ZSPFBAPIENTRADA getZSPFBAPIENTRADA() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZSPF_BAPI_ENTRADA"), ZSPFBAPIENTRADA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZSPFBAPIENTRADA
     */
    @WebEndpoint(name = "ZSPF_BAPI_ENTRADA")
    public ZSPFBAPIENTRADA getZSPFBAPIENTRADA(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZSPF_BAPI_ENTRADA"), ZSPFBAPIENTRADA.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZSPFBAPIENTRADA_EXCEPTION!= null) {
            throw ZSPFBAPIENTRADA_EXCEPTION;
        }
        return ZSPFBAPIENTRADA_WSDL_LOCATION;
    }

}
