package sap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZSPF_BAPI_ENTRADA", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZSPFBAPIENTRADA {


    /**
     * 
     * @param entrada
     * @return
     *     returns io.cronapp.sap.ZBapireturn1
     */
    @WebMethod(operationName = "ZhrplanferiasEntrada", action = "http://www.sap.com/ZhrplanferiasEntrada")
    @WebResult(name = "Return", targetNamespace = "")
    @RequestWrapper(localName = "ZhrplanferiasEntrada", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "io.cronapp.sap.ZhrplanferiasEntrada")
    @ResponseWrapper(localName = "ZhrplanferiasEntradaResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "io.cronapp.sap.ZhrplanferiasEntradaResponse")
    public ZBapireturn1 zhrplanferiasEntrada(
        @WebParam(name = "Entrada", targetNamespace = "")
        ZctHrBapiEntradaSpf entrada);

}
