
package sap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZSPF_BAPI_SAIDA", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/build/cronapp/wsdl_saida.xml")
public class ZSPFBAPISAIDA_Service
    extends Service
{

    private final static URL ZSPFBAPISAIDA_WSDL_LOCATION;
    private final static WebServiceException ZSPFBAPISAIDA_EXCEPTION;
    private final static QName ZSPFBAPISAIDA_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZSPF_BAPI_SAIDA");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/build/cronapp/wsdl_saida.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZSPFBAPISAIDA_WSDL_LOCATION = url;
        ZSPFBAPISAIDA_EXCEPTION = e;
    }

    public ZSPFBAPISAIDA_Service() {
        super(__getWsdlLocation(), ZSPFBAPISAIDA_QNAME);
    }

    public ZSPFBAPISAIDA_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZSPFBAPISAIDA_QNAME, features);
    }

    public ZSPFBAPISAIDA_Service(URL wsdlLocation) {
        super(wsdlLocation, ZSPFBAPISAIDA_QNAME);
    }

    public ZSPFBAPISAIDA_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZSPFBAPISAIDA_QNAME, features);
    }

    public ZSPFBAPISAIDA_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZSPFBAPISAIDA_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZSPFBAPISAIDA
     */
    @WebEndpoint(name = "ZSPF_BAPI_SAIDA")
    public ZSPFBAPISAIDA getZSPFBAPISAIDA() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZSPF_BAPI_SAIDA"), ZSPFBAPISAIDA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZSPFBAPISAIDA
     */
    @WebEndpoint(name = "ZSPF_BAPI_SAIDA")
    public ZSPFBAPISAIDA getZSPFBAPISAIDA(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZSPF_BAPI_SAIDA"), ZSPFBAPISAIDA.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZSPFBAPISAIDA_EXCEPTION!= null) {
            throw ZSPFBAPISAIDA_EXCEPTION;
        }
        return ZSPFBAPISAIDA_WSDL_LOCATION;
    }

}
